package:
    name: "pylhapdf"
    version: "0.1"

source:
    path: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - cython
        - meson
        - ninja
    host:
        - pkgconfig
        - cython
        - lhapdf
        - numpy
        - python
    run:
        - lhapdf
        - numpy

test:
  imports:
    - pylhapdf

about:
    home: "https://zigzah.com"
    licence: "SECRET"
