name: CI

on: [push]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ["3.8", "3.9"]

        runs-on: ${{ matrix.os }}

        steps:
          - uses: actions/checkout@v2

          - uses: conda-incubator/setup-miniconda@v2
            with:
                mamba-version: "*"
                python-version: ${{ matrix.python-version }}
                channels: "https://packages.nnpdf.science/conda,conda-forge,defaults"

          - name: Run a multi-line script
            shell: bash -l {0}
            run: |
                conda activate
                conda install boa --yes
                conda mambabuild conda-recipe
