name: CI

on: [push]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: ["3.8", "3.9"]

        runs-on: ${{ matrix.os }}

        steps:

          - uses: actions/checkout@v2

          - uses: conda-incubator/setup-miniconda@v2
            with:
                mamba-version: "*"
                python-version: ${{ matrix.python-version }}
                channels: "https://packages.nnpdf.science/conda,conda-forge"

          - name: Install macOS SDK
            if: startsWith(matrix.os, 'macOS')
            shell: bash -l {0}
            run: |
                conda activate test
                curl -L -O https://data.nnpdf.science/MacOSX10.9.sdk.tar.xz
                tar xfz MacOSX10.9.sdk.tar.xz -C $CONDA_PREFIX

          - name: Run a multi-line script
            shell: bash -l {0}
            run: |
                conda activate
                conda install boa --yes
                conda mambabuild conda-recipe

          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
                key: ${{ secrets.SSH_KEY }}
                known_hosts: ${{ secrets.KNOWN_HOSTS }}

          - name: Upload
            shell: bash -l {0}
            run: |
                if [ "$RUNNER_OS" = "Linux" ]; then
                    OSFOLDER=linux-64
                elif [ "$RUNNER_OS" = "macOS" ]; then
                    OSFOLDER=osx-64
                else
                    exit 41
                fi
                scp ${CONDA_PREFIX}/conda-bld/${OSFOLDER}/*.tar.bz2 dummy@packages.nnpdf.science:~/packages/conda/${OSFOLDER}

